import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { formatDate } from "@nyumba360/shared";
import type { ReportTable, ReportRange } from "@/lib/reports";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, color: "#16261f", fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  brand: { fontSize: 16, fontWeight: "bold", color: "#147a55" },
  org: { fontSize: 9, color: "#5b6b64" },
  title: { fontSize: 13, fontWeight: "bold" },
  range: { fontSize: 9, color: "#5b6b64", marginBottom: 12 },
  summaryRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  summaryBox: { padding: 8, backgroundColor: "#f0f7f3", borderRadius: 4, minWidth: 110 },
  summaryLabel: { fontSize: 8, color: "#5b6b64" },
  summaryValue: { fontSize: 12, fontWeight: "bold", color: "#147a55", marginTop: 2 },
  thead: { flexDirection: "row", borderBottom: "1pt solid #147a55", paddingBottom: 4, marginBottom: 2 },
  th: { flex: 1, fontWeight: "bold", fontSize: 9 },
  tr: { flexDirection: "row", paddingVertical: 3, borderBottom: "0.5pt solid #e5eae7" },
  td: { flex: 1, fontSize: 9 },
  footer: { marginTop: 20, fontSize: 8, color: "#8a9690" },
});

function ReportDoc({ table, range, orgName }: { table: ReportTable; range: ReportRange; orgName: string }) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brand}>LogiQ Estates Pro</Text>
            <Text style={styles.org}>{orgName}</Text>
          </View>
          <View>
            <Text style={styles.title}>{table.title}</Text>
          </View>
        </View>
        <Text style={styles.range}>
          {formatDate(range.from)} — {formatDate(range.to)}
        </Text>

        <View style={styles.summaryRow}>
          {table.summary.map((s) => (
            <View key={s.label} style={styles.summaryBox}>
              <Text style={styles.summaryLabel}>{s.label}</Text>
              <Text style={styles.summaryValue}>{s.value}</Text>
            </View>
          ))}
        </View>

        <View style={styles.thead}>
          {table.columns.map((c) => (
            <Text key={c} style={styles.th}>
              {c}
            </Text>
          ))}
        </View>
        {table.rows.map((row, i) => (
          <View key={i} style={styles.tr} wrap={false}>
            {row.map((cell, j) => (
              <Text key={j} style={styles.td}>
                {cell}
              </Text>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>Generated by LogiQ Estates Pro on {formatDate(new Date())}.</Text>
      </Page>
    </Document>
  );
}

export async function renderReport(table: ReportTable, range: ReportRange, orgName: string): Promise<Uint8Array> {
  return renderToBuffer(<ReportDoc table={table} range={range} orgName={orgName} />);
}
